#
# This travis config file is intended to be used by LifterLMS Add-ons.
#
# Example usage in .travis.yml:
#
# import:
#  - gocodebox/lifterlms:.config/travis/add-on.yml
#

# Import main configs.
import:
  - gocodebox/lifterlms:.config/travis/main.yml

# If $LLMS_BRANCH is specified, install the plugin from git.
install:
  - |
    if [ ! -z "$LLMS_BRANCH" ]; then
      ./vendor/bin/llms-tests plugin https://github.com/gocodebox/lifterlms.git@${LLMS_BRANCH}
    fi

# Test against the "nightly" dev branch of the the LifterLMS core.
jobs:
  include:
  - php: "8.0"
    env:  LLMS_BRANCH=dev WP_VERSION=latest
