#
# TravisCI config file partial for running an eslint job
#
# This partial is intended to be used alongside the main.yml config found within this same directory.
#
# Example usage in .travis.yml:
#
# import:
#  - gocodebox/lifterlms:.config/travis/main.yml
#  - gocodebox/lifterlms:.config/travis/eslint.yml
#

jobs:
  include:
  - env: ESLINT=1
    language: node_js
    node_js: lts/*
    before_install:
    install:
      - npm ci
    script:
      - npm run lint:js
    after_script:
