###
#
# Custom workflow matrix configurations
#
# @link https://github.com/gocodebox/.github/tree/trunk/.github/actions/setup-matrix
#
###
Test PHPUnit:
  __delete:
    # Remove the LLMS Nightly job (intended for add-ons).
    - include[1]
